-- Tạo cơ sở dữ liệu QL_SINHVIEN
CREATE DATABASE QL_LINHKIEN;
GO
-- Sử dụng cơ sở dữ liệu QL_LINHKIEN
USE QL_LINHKIEN;
GO

CREATE TABLE LOAILK (
	MALOAI CHAR(10),
	TENLOAI NVARCHAR(50),
	CONSTRAINT PK_MALOAI PRIMARY KEY(MALOAI)
)

CREATE TABLE LINHKIEN (
	MALK CHAR(10),
	TENLK NVARCHAR(50),
	NGAYSX DATE,
	TGBH INT,
	MALOAI CHAR(10),
	NSX NVARCHAR(20),
	DVT NVARCHAR(10),
	CONSTRAINT PK_MALK PRIMARY KEY(MALK),
	CONSTRAINT FK_MALOAI FOREIGN KEY(MALOAI) REFERENCES LOAILK(MALOAI)
)

CREATE TABLE KHACHHANG (
	MAKH CHAR(10),
	TENKH NVARCHAR(50),
	DCHI NVARCHAR(50),
	DTHOAI CHAR(11),
	CONSTRAINT PK_MAKH PRIMARY KEY(MAKH)
)

CREATE TABLE HOADON (
	MAHD CHAR(10),
	NGAYHD DATE,
	MAKH CHAR(10),
	TONGTIEN FLOAT NULL,
	CONSTRAINT PK_MAHD PRIMARY KEY(MAHD),
	CONSTRAINT FK_MAKH_2 FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CHITIETHOADON (
	MAHD CHAR (10),
	MALK CHAR (10),
	SOLUONG INT,
	DONGIA FLOAT,
	CONSTRAINT PK_MAHD_MAKH PRIMARY KEY(MAHD, MALK),
	CONSTRAINT FK_MAHD_2 FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_MALK FOREIGN KEY (MALK) REFERENCES LINHKIEN(MALK)
)

INSERT INTO LOAILK VALUES
('MOU', N'Chuột'),
('LAP', N'Máy tính xách tay'),
('CPU', N'Bộ xử lý'),
('PCX', N'Máy tính để bàn'),
('MAI', N'Mainboard')

INSERT INTO LINHKIEN VALUES 
(N'MOU001', N'Chuột quang có dây', '2014-01-01', 12, N'MOU', N'Genius', N'Cái'),
(N'MOU002', N'Chuột quang không dây', '2015-02-04', 12, N'MOU', N'Mitsumi', N'Cái'),
(N'MOU003', N'Chuột không dây', '2014-04-02', 24, N'MOU', N'Abroad', N'Cái'),
(N'CPU001', N'CPU AMD', '2015-04-05', 24, N'CPU', N'Abroad', N'Cái'),
(N'CPU002', N'CPU INTEL', '2016-02-07', 36, N'CPU', N'Mitsumi', N'Cái'),
(N'CPU003', N'CPU ASUS', '2015-12-08', 36, N'CPU', N'Abroad', N'Cái'),
(N'MAI001', N'Mainboard ASUS', '2015-12-04', 36, N'MAI', N'Mitsumi', N'Cái'),
(N'MAI002', N'Mainboard ATXX', '2016-03-03', 12, N'MAI', N'Mitsumi', N'Cái'),
(N'MAI003', N'Mainboard ACER', '2015-04-14', 12, N'MAI', N'Genius', N'Cái'),
(N'PCX001', N'ACER 20144', '2015-10-19', 12, N'PCX', N'Genius', N'Bộ')

INSERT INTO KHACHHANG VALUES 
('KH001', N'Nguyễn Thu Tâm', N'Tây Ninh', '0989751723'),
('KH002', N'Đinh Bảo Lộc', N'Lâm Đồng', '09188234654'),
('KH003', N'Trần Thanh Diệu', N'TP.HCM', '0978123765'),
('KH004', N'Hồ Tuấn Thành', N'Hà Nội', '0909456768'),
('KH005', N'Huỳnh Kim Ánh', N'Khánh Hòa', '0932987567')

INSERT INTO HOADON VALUES 
('HD001', '2015-04-01', 'KH001', NULL),
('HD002', '2016-05-15', 'KH005', NULL),
('HD003', '2016-06-14', 'KH004', NULL),
('HD004', '2016-06-03', 'KH005', NULL),
('HD005', '2016-06-05', 'KH001', NULL),
('HD006', '2016-07-07', 'KH003', NULL),
('HD007', '2016-08-12', 'KH002', NULL),
('HD008', '2016-09-25', 'KH003', NULL)

INSERT INTO CHITIETHOADON VALUES
('HD001', 'MOU001', 2, 1000000),
('HD002', 'MOU002', 1, 2000000),
('HD003', 'MOU003', 6, 3000000),
('HD004', 'CPU001', 5, 500000),
('HD005', 'CPU002', 6, 560000),
('Hd006', 'CPU003', 3, 400000),
('HD006', 'MAI001', 1, 200000),
('HD007', 'MAI002', 1, 150000),
('HD007', 'MAI003', 2, 160000),
('HD007', 'MOU001', 1, 1000000),
('HD008', 'CPU001', 2, 500000)

select * from LOAILK;
select * from LINHKIEN;
select * from KHACHHANG;
select * from HOADON;
select * from CHITIETHOADON;

-- Câu 1: Cập nhật tổng tiền cho mỗi hóa đơn = tổng hóa đơn (số lượng x đơn giá)

UPDATE HOADON
SET TONGTIEN = (
	SELECT SUM(SOLUONG * DONGIA)
	FROM CHITIETHOADON
	WHERE CHITIETHOADON.MAHD = HOADON.MAHD
)

-- câu 2: cho biết tên linh kiện nsx là genius và có đơn vị tính là cái

SELECT TENLK
FROM LINHKIEN
WHERE NSX='Genius' AND DVT=N'Cái';

-- câu 3: thông tin liên kiện có TGBH là 24 tháng

SELECT *
FROM LINHKIEN
WHERE TGBH=24;

-- câu 4: hóa đơn nào đc lập trong 06/2016

SELECT *
FROM HOADON
WHERE NGAYHD LIKE '2016-06-%';

-- câu 5: Tên và DVT LK có đơn giá > 1000000

SELECT TENLK, DVT
FROM CHITIETHOADON, LINHKIEN
WHERE CHITIETHOADON.MALK = LINHKIEN.MALK AND DONGIA >= 1000000;

-- câu 6: thông tin MALK, TENLK, NSX, DVT được bán trước ngày 31/05/2015

SELECT LINHKIEN.MALK, TENLK, NSX, DVT
FROM LINHKIEN, CHITIETHOADON, HOADON
WHERE CHITIETHOADON.MALK = LINHKIEN.MALK AND HOADON.MAHD = CHITIETHOADON.MAHD
AND HOADON.NGAYHD < '2015-05-31';

-- câu 7: Danh sách các KH mua LK trong 06/2016 có địa chỉ ở TP.HCM

SELECT KHACHHANG.*
FROM KHACHHANG, CHITIETHOADON, HOADON
WHERE KHACHHANG.MAKH = HOADON.MAKH AND HOADON.MAHD = CHITIETHOADON.MAHD
AND KHACHHANG.DCHI = 'TP.HCM';

-- câu 8: cho biết tổng số lượng LK của HD007

SELECT MAHD, SUM(SOLUONG) AS 'So Luong'
FROM CHITIETHOADON
WHERE MAHD='HD007'
GROUP BY MAHD;

-- câu 9: trog tháng 5/2016 có bao nhiêu khách ở Tây Ninh tới mua hàng

SELECT COUNT(MAKH) as N'Số lượng khách'
FROM KHACHHANG
WHERE MAKH IN (
	SELECT HOADON.MAKH
	FROM HOADON
	WHERE NGAYHD LIKE '2016-05-%'
) AND KHACHHANG.DCHI = 'Tây Ninh';

-- câu 10: DTHOAI và DCHI của KH001 

SELECT DTHOAI, DCHI
FROM KHACHHANG
WHERE MAKH = 'KH001';

-- câu 11: trong 05/2016 đã lập bao nhiêu đơn hàng:

SELECT hd.MAHD, COUNT(hd.MAHD) AS 'Số lượng đơn'
FROM CHITIETHOADON, HOADON hd
WHERE CHITIETHOADON.MAHD = hd.MAHD AND NGAYHD LIKE '2016-05-%'
GROUP BY hd.MAHD;

-- câu 13: tổng tiền HD005 và HD007

SELECT SUM(HOADON.TONGTIEN) AS N'Tổng tiền'
FROM HOADON, CHITIETHOADON
WHERE HOADON.MAHD = CHITIETHOADON.MAHD AND HOADON.MAHD = 'HD005' OR HOADON.MAHD = 'HD007';

-- câu 12: Tổng tiền HD006

SELECT SUM(HOADON.TONGTIEN) AS N'Tổng tiền'
FROM HOADON, CHITIETHOADON
WHERE HOADON.MAHD = CHITIETHOADON.MAHD AND HOADON.MAHD = 'HD006';

-- câu 14: 

SELECT CTHD.MAHD, COUNT(DISTINCT CTHD.MALK) 
FROM HOADON HD, CHITIETHOADON CTHD
WHERE HD.MAHD = CTHD.MAHD
GROUP BY CTHD.MAHD

-- câu 15: Tên NSX và số LK đã bán của từng NSX

SELECT NSX, lk.TENLK, COUNT(lk.MALK) AS 'SỐ LƯỢNG'
FROM LINHKIEN lk, CHITIETHOADON cthd
WHERE lk.MALK = cthd.MALK
GROUP BY NSX, lk.TENLK;

-- câu 16: MAHD và tổng tiền từng HD

SELECT hd.MAHD, SUM(hd.TONGTIEN) AS 'TỔNG TIỀN'
FROM HOADON hd, CHITIETHOADON cthd
WHERE hd.MAHD = cthd.MAHD
GROUP BY hd.MAHD;

-- câu 17: Danh sách tên KH và MAHD có tổng tiền > 1m

SELECT kh.TENKH, hd.MAHD, SUM(hd.TONGTIEN) AS 'TỔNG TIỀN'
FROM HOADON hd, CHITIETHOADON cthd, KHACHHANG kh
WHERE hd.MAHD = cthd.MAHD AND hd.MAKH = kh.MAKH
GROUP BY kh.TENKH, hd.MAHD;

-- câu 18: Mỗi loại LK có bao nhieu LK

SELECT LOAILK.MALOAI, COUNT(MALK)
FROM LINHKIEN, LOAILK
WHERE LINHKIEN.MALOAI = LOAILK.MALOAI
GROUP BY LOAILK.MALOAI;

-- câu 19: MAHD có số lượng LK > 10

SELECT MAHD, SUM(SOLUONG)
FROM CHITIETHOADON
GROUP BY MAHD
HAVING SUM(SOLUONG)>10

-- câu 20: trị giá HD lập ngày 7/7/2016

SELECT SUM(HOADON.TONGTIEN) AS N'Tổng tiền'
FROM HOADON, CHITIETHOADON
WHERE HOADON.MAHD = CHITIETHOADON.MAHD AND HOADON.NGAYHD = '2016-07-07';

-- câu 21: tên và sl của từng mặt hàng trong HD007

SELECT lk.TENLK, SUM(cthd.SOLUONG) AS 'SỐ LƯỢNG'
FROM CHITIETHOADON cthd, LINHKIEN lk
WHERE cthd.MALK = lk.MALK AND cthd.MAHD = 'HD007'
GROUP BY lk.TENLK;