-- Tạo cơ sở dữ liệu QL_SINHVIEN
CREATE DATABASE QL_SINHVIEN;
GO
-- Sử dụng cơ sở dữ liệu QL_SINHVIEN
USE QL_SINHVIEN;
GO

-- Tạo bảng KHOA
CREATE TABLE KHOA (
    MAKH VARCHAR(10),
    TENKH NVARCHAR(50),
	CONSTRAINT PK_KHOA PRIMARY KEY(MAKH)
);

-- Tạo bảng LOP
CREATE TABLE LOP (
    MALOP VARCHAR(10),
    TENLOP NVARCHAR(50),
    SISO INT,
    LOPTRUONG NVARCHAR(10),
    MAKH VARCHAR(10),
	CONSTRAINT PK_LOP PRIMARY KEY(MALOP),
    CONSTRAINT FK_LOP FOREIGN KEY (MAKH) REFERENCES KHOA(MAKH)
);

-- Tạo bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MASV VARCHAR(10),
    HOTEN NVARCHAR(50),
    NGSINH DATE,
    GTINH NVARCHAR(3),
    DCHI NVARCHAR(100),
    MALOP VARCHAR(10),
	CONSTRAINT PK_SINHVIEN PRIMARY KEY(MASV),
	CONSTRAINT FK_SINHVIEN FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);


-- Tạo bảng GIANGVIEN
CREATE TABLE GIANGVIEN (
    MAGV VARCHAR(10),
    TENGV NVARCHAR(50),
    MAKH VARCHAR(10),
    CONSTRAINT PK_GIANGVIEN PRIMARY KEY(MAGV),
	CONSTRAINT FK_GIANGVIEN FOREIGN KEY (MAKH) REFERENCES KHOA(MAKH)
);

-- Tạo bảng MONHOC
CREATE TABLE MONHOC (
    MAMH VARCHAR(10),
    TENMH NVARCHAR(50),
    SOTC INT,
	CONSTRAINT PK_MONHOC PRIMARY KEY(MAMH),
);

-- Tạo bảng DIEM
CREATE TABLE DIEM (
    MASV VARCHAR(10),
    MAMH VARCHAR(10),
    LANTHI INT,
    DIEMTHI FLOAT,
    CONSTRAINT PK_DIEM PRIMARY KEY (MASV, MAMH, LANTHI),
    CONSTRAINT FK_DIEM FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT FK_DIEM2 FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
);

-- Tạo bảng GIANGDAY
CREATE TABLE GIANGDAY (
    MAGV VARCHAR(10),
    MAMH VARCHAR(10),
    NAMHOC NVARCHAR(10),
    HOCKY NVARCHAR(5),
    CONSTRAINT PK_GIANGDAY PRIMARY KEY (MAGV, MAMH, NAMHOC, HOCKY),
    CONSTRAINT FK_GIANGDAY FOREIGN KEY (MAGV) REFERENCES GIANGVIEN(MAGV),
    CONSTRAINT FK_GIANGDAY2 FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
);

-- Tạo bảng THANNHAN
CREATE TABLE THANNHAN (
    MATN VARCHAR(10),
    HOTEN NVARCHAR(50),
    GIOITINH NVARCHAR(3),
	CONSTRAINT PK_THANNHAN PRIMARY KEY(MATN)
);

-- Tạo bảng QUANHE
CREATE TABLE QUANHE (
    MATN VARCHAR(10),
    MASV VARCHAR(10),
    QUANHE NVARCHAR(20),
    CONSTRAINT PK_QUANHE PRIMARY KEY (MATN, MASV),
    CONSTRAINT FK_QUANHE FOREIGN KEY (MATN) REFERENCES THANNHAN(MATN),
    CONSTRAINT FK_QUANHE2 FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)
);
-- Thêm dữ liệu vào bảng KHOA (dựa trên dữ liệu ở các bảng khác)
INSERT INTO KHOA VALUES
('SH', N'Công Nghệ Sinh học'),
('TH', N'Công Nghệ Thông Tin'),
('TC', N'Công Nghệ Tài chính'),
('TP', N'Công Nghệ Thực phẩm'),
('QT', N'Quản Trị Kinh Doanh')

-- Thêm dữ liệu vào bảng LOP
INSERT INTO LOP(MALOP,TENLOP,SISO,LOPTRUONG,MAKH) VALUES
('10DHSH1', N'10 Đại học Sinh học 1', 55, 'SV008', 'SH'),
('10DHTH1', N'10 Đại học Tin học 1', 50, 'SV001', 'TH'),
('11DHTH2', N'11 Đại học Tin học 2', 40, 'SV005', 'TH'),
('12DHTC1', N'12 Đại học Tài chính 1', 75, 'SV009', 'TC'),
('12DHTP1', N'12 Đại học Thực phẩm 1', 60, 'SV007', 'TP')

-- Thêm dữ liệu vào bảng SINHVIEN
INSERT INTO SINHVIEN (MASV, HOTEN, NGSINH, GTINH, DCHI, MALOP) VALUES
('SV001', N'Trần Lệ Quyên', '1995-01-21', N'Nữ', N'TPHCM', '10DHTH1'),
('SV002', N'Nguyễn Thế Bình', '1996-06-04', N'Nam', N'Tây Ninh', '11DHTH2'),
('SV003', N'Tô Ánh Nguyệt', '1995-05-02', N'Nữ', N'Vũng Tàu', '12DHTP1'),
('SV004', N'Nguyễn Thế Anh', '1996-12-15', N'Nam', N'Đồng Nai', '12DHTP1'),
('SV005', N'Lê Thanh Bình', '1994-12-09', N'Nam', N'Long An', '11DHTH2'),
('SV006', N'Phạm Quang Hậu', '1995-10-12', N'Nam', N'Tây Ninh', '10DHTH1'),
('SV007', N'Lê Cẩm Tú', '1989-02-13', N'Nữ', N'Bình Thuận', '12DHTP1'),
('SV008', N'Trương Thế Sang', '1993-04-04', N'Nam', N'Bình Dương', '10DHSH1'),
('SV009', N'Đậu Quang Ánh', '1994-12-03', N'Nam', N'Long An', '12DHTC1'),
('SV010', N'Huỳnh Kim Chi', '1996-10-18', N'Nữ', N'TPHCM', '11DHTH2'),
('SV011', N'Trịnh Đình Ánh', '1995-11-15', N'Nam', N'Bình Thuận', '10DHTH1')

-- Thêm dữ liệu vào bảng GIANGVIEN
INSERT INTO GIANGVIEN (MAGV, TENGV, MAKH) VALUES
('GV001', N'Phạm Thế Bảo', 'TH'),
('GV002', N'Lê Thể Truyền', 'TH'),
('GV003', N'Trương Anh Dũng', 'SH'),
('GV004', N'Bùi Chí Anh', 'TC'),
('GV005', N'Lê Công Hậu', 'QT'),
('GV006', N'Lê Trung Thành', 'TP');

-- Thêm dữ liệu vào bảng MONHOC
INSERT INTO MONHOC (MAMH, TENMH, SOTC) VALUES
('CSDL', N'Cơ sở dữ liệu', 3),
('KTLT', N'Kỹ thuật lập trình', 3),
('THVP', N'Tin học văn phòng', 3),
('TRR', N'Toán rời rạc', 3),
('TTNT', N'Trí tuệ nhân tạo', 2),
('TTQT', N'Thanh toán quốc tế', 2);
-- Thêm dữ liệu vào bảng DIEM
INSERT INTO DIEM (MASV, MAMH, LANTHI, DIEMTHI) VALUES
('SV001', 'CSDL', 1, 9),
('SV002', 'THVP', 1, 3),
('SV002', 'THVP', 2, 7),
('SV004', 'THVP', 1, 6),
('SV004', 'CSDL', 1, 5),
('SV005', 'CSDL', 1, 3),
('SV005', 'CSDL', 2, 6),
('SV006', 'KTLT', 1, 4),
('SV009', 'TTQT', 1, 4),
('SV010', 'THVP', 1, 8),
('SV010', 'TRR', 1, 7);

-- Thêm dữ liệu vào bảng GIANGDAY
INSERT INTO GIANGDAY (MAGV, MAMH, NAMHOC, HOCKY) VALUES
('GV001', 'CSDL', '2021-2022', '1'),
('GV001', 'KTLT', '2020-2021', '2'),
('GV001', 'TTNT', '2020-2021', '1'),
('GV002', 'CSDL', '2021-2022', '2'),
('GV002', 'KTLT', '2021-2022', '2');

-- Thêm dữ liệu vào bảng THANNHAN
INSERT INTO THANNHAN (MATN, HOTEN, GIOITINH) VALUES
('TN001', N'Nguyễn Thế Thành', 'Nam'),
('TN002', N'Tô Ánh Hồng', 'Nữ'),
('TN003', N'Lê Thanh An', 'Nam'),
('TN004', N'Phạm Thanh Tiền', 'Nữ'),
('TN006', N'Đậu Văn Thanh', 'Nam'),
('TN007', N'Nguyễn Thị Ánh', 'Nữ'),
('TN008', N'Lê Quang Định', 'Nam'),
('TN009', N'Huỳnh Văn Tư', 'Nam');
-- Thêm dữ liệu vào bảng QUANHE
INSERT INTO QUANHE (MATN, MASV, QUANHE) VALUES
('TN001', 'SV002', 'Bố'),
('TN003', 'SV005', 'Bố'),
('TN004', 'SV007', 'Mẹ'),
('TN006', 'SV009', 'Bố'),
('TN007', 'SV002', 'Mẹ'),
('TN008', 'SV005', 'Bố'),
('TN008', 'SV007', 'Bố');

--CAP NHAP DCHI CUA SV002 LA CAN THO
UPDATE SINHVIEN
SET DCHI='Cần Thơ'
WHERE MASV='SV002';

--TAO BẢNG ÃO LƯU TRỮ DANH SÁCH SV (MASV VÀ HOTEN) , TÊN LOP

CREATE VIEW DANHSACHSINHVIEN AS
SELECT SV.MASV,SV.HOTEN,LH.TENLOP
FROM SINHVIEN SV
JOIN LOP LH ON SV.MALOP=LH.MALOP;

--liet ke DS SINH VIEN Ơ VUNGTAU

SELECT MASV,HOTEN
FROM SINHVIEN
WHERE DCHI=N'Vũng Tàu';

--SO TC MON TOAN ROI RAC
SELECT SOTC
FROM MONHOC
WHERE TENMH=N'Toán rời rạc';

--danh sach lop thuoc khoa cong nghe tt
SELECT L.TENLOP
FROM LOP L
JOIN KHOA K ON L.MAKH = K.MAKH
WHERE K.TENKH = N'Công Nghệ Thông Tin';

--SV co ho nguyễn
SELECT MASV,HOTEN
FROM SINHVIEN
WHERE HOTEN LIKE N'NGUYỄN%'

---LK DS TEN KHOA VÀ SỐ LƯỢNG SV TỪNG KHOA
SELECT TENKH, COUNT(MALOP) AS N'TỔNG SỐ LỚP'
FROM KHOA,LOP
WHERE KHOA.MAKH=LOP.MAKH
GROUP BY TENKH

---LIET KE TENLOP VA SL SV TUNG LOP

SELECT TENLOP,(SELECT COUNT(*) 
				FROM SINHVIEN
				WHERE SINHVIEN.MALOP=LOP.MALOP) AS SLSV
FROM LOP

---LIETKE DS TEN KHOA BA SL SV TUNG KHOA , SAP XEP KHOA THEO SLSV TANG DAN
SELECT TENKH,(SELECT COUNT(*) 
				FROM LOP
				WHERE LOP.MAKH=KHOA.MAKH AND EXISTS (SELECT 1 FROM SINHVIEN S WHERE S.MALOP = LOP.MALOP)
				)AS SLSV  
FROM KHOA
ORDER BY SLSV ASC; 

--LIET KÊ MÃ SV HỌ TÊN ĐIỂM TB
SELECT MASV,HOTEN,(SELECT AVG(DIEMTHI)
					FROM DIEM
					)AS DTB
FROM SINHVIEN

--CHO BIET HO TEN VA TONG SO MON SV NAM DA HOC
SELECT S.HOTEN,(SELECT COUNT(DISTINCT D.MAMH)
						FROM DIEM D
						WHERE D.MASV=S.MASV
				)AS TONGSOMON
FROM SINHVIEN S
WHERE S.GTINH=N'Nam'; 





